export enum Role {
  ROLE_ADMIN_SCHOOL = 'ROLE_ADMIN_SCHOOL',
  ROLE_AGENT = 'ROLE_AGENT',
  ROLE_STUDENT = 'ROLE_STUDENT',
  ROLE_ADMIN_MELIO = 'ROLE_ADMIN_MELIO',
  ROLE_SUPERADMIN = 'ROLE_SUPERADMIN',
}
